version: '3'

services:
 api:
  build: ./
  command: npm run start
  restart: unless-stopped
  ports:
    - "4200:4200"
  depends_on:
    - mongoDataBase
  networks: 
    - megasaab-docker-network
 
 mongoDataBase:
  image: 'mongo'
  volumes:
    - mongodb_api:/data/db
  networks: 
    - megasaab-docker-network

volumes:
 mongodb_api:

networks: 
  megasaab-docker-network:
    driver: bridge