version: '3'

services:
 api:
  build: ./
  command: npm run start
  restart: unless-stopped
  ports:
    - "${PORT}:${PORT}"
  environment: 
    VIRTUAL_HOST: ${VIRTUAL_HOST}
    VIRTUAL_PORT: ${PORT}
    LETSENCRYPT_HOST: ${VIRTUAL_HOST}
    LETSENCRYPT_EMAIL: azhg.sabyrzhan@gmail.com
  depends_on:
    - mongoDataBase
  networks: 
    - megasaab-docker-network
    - https
 
 mongoDataBase:
  image: 'mongo'
  volumes:
    - mongodb_api:/data/db
  networks: 
    - megasaab-docker-network

volumes:
 mongodb_api:

networks: 
  https:
    external:
      name: https_network
  megasaab-docker-network:
    driver: bridge